### PR TITLE
Release 0.21.2

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
At @jchodera when you get a chance can you look at this and approve it if it looks good?
Once this gets merged @ijpulidos we can get the CLI PR merged in, but I think we should do a re-build of the perses conda-forge package and set the minimum version for openmmtools to this version so that the CLI will work consistently. Another option is I could just build the docker image with the right openmmtools version, but it would be really annoying for someone to download perses and then try to test the CLI to then get hit with an error. Thoughts?

**Comment by ijpulidos** [comment]
I agree with you. I guess the easier way is to get this released and then pin a minimum openmmtools version for the upcoming perses release with the new CLI. The other option seems like it might get confusing for users, in my opinion. I know there are still some things to think about form the perses side.

**Review by ijpulidos — APPROVED** [review]
Looks good! Thanks.

**Review by jchodera — APPROVED** [review]
Thanks!

**Pull request merged**
